### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by ExplosionGaming** [aieuo/Mineflow#104]
### Question

![image](https://user-images.githubusercontent.com/92651856/149245343-d4cf4c31-caf6-410e-b9f9-a07ea166dd2f.png)

How do I make these activate a recipe?

### Plugin Version

Mineflow_dev-226

**Comment by keenanyafiqy** [comment]
wut is that

**Comment by keenanyafiqy** [comment]
i wasn't even trying the plugin tho

**Comment by sweatyrayan** [comment]
What do you mean?
If you want to activate a recipe if the player fly´s, then just set the trigger of the recipe to ´When a player toggles their flying state´

**Comment by ExplosionGaming** [comment]
> What do you mean? If you want to activate a recipe if the player fly´s, then just set the trigger of the recipe to ´When a player toggles their flying state´

No, I mean like when the turn the toggle button on and summit the form they get fly. I just don't know how to make those toggle buttons to activate something.

**Comment by sweatyrayan** [comment]
I think there is no action to let the player fly.

![IMG_0366](https://user-images.githubusercontent.com/59512147/149616655-6a9c8def-7e26-41f2-b5e8-da55525a7719.jpeg)

This recipe sets the target gamemode to creative if they toggle the button to true.

**Comment by ExplosionGaming** [comment]
Thanks

**Comment by ExplosionGaming** [comment]
> I think there is no action to let the player fly. Maybe add it by yourself or download a plugin.
> 
> ![IMG_0366](https://user-images.githubusercontent.com/59512147/149616655-6a9c8def-7e26-41f2-b5e8-da55525a7719.jpeg)
> 
> This recipe sets the target gamemode to creative if they toggle the button to true.

Where is that condition?

**Comment by sweatyrayan** [comment]
Sorry for the late reaction, but you need to add the condition.

Edit condition > Script > Compare to the character string > Add > first value = {form.data[0]}, second value = true > Submit
