### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by HugePvP** [aieuo/Mineflow#107]
Do you know how to setup ScoreHUD with mineflow

**Comment by HugePvP** [comment]
?

**Comment by aieuo** [comment]
ScoreHUD and mineflow are not compatible.  

To show scoreboards with mineflow, you can use these actions.   
![image](https://user-images.githubusercontent.com/35859665/150286631-e77aa746-153e-429f-a6fa-b12f840b30d3.png)

**Comment by HugePvP** [comment]
How do I get there tho

**Comment by aieuo** [comment]
Click the `<Edit action>` > `<Add action>` > `Scoreboard` buttons on your recipe.
