### ISSUE TITLE
Can you Make a CommandCreator Plugin

### ISSUE THREAD

**Issue by DragonfireHD** [aieuo/Mineflow#11]
I write on german you musr translate i have a bad English 

Dieses Plugin soll so aufgebaut werden das man commands manuell erstellen kann in der config ich weiß es gibt bereits so ein plugin auf poggit aber das hat mega Probleme zmb können andere Spieler die Commands in der Befehlliste nicht sehen nur die OP haben können es sehen normalerweise kann man die permission ausschalten aber dennoch kann nur die OP leute die Befehle in der liste sehen aber die Spieler mit einem anderen Rang nicht es wäre nett wenn du sowas machen könntest

For a good Cooperation->
DragonfireHD98

**Comment by Johnsonk79** [comment]
they can be created in config if you know how to.

**Comment by DragonfireHD** [comment]
Was meinst du jetzt??

Ich meine das dass plugin bereits gibt nur paar fehler hat und ich dachte ihr könnt vielleicht es reparieren denn es geht darum das andere Spieler die commands sehen können wenn man sie erstellt hat aber das tut es nicht nur wenn ich op mir gebe sehe ich die Commands außerdem die commands können bei normalen spielern ausgeführt werden aber man sieht die /befehlliste für diesen command nicht

**Comment by DragonfireHD** [comment]
I send a picture

**Comment by Johnsonk79** [comment]
Using mine flow, all they commands are in the config after you create them, which I think means if you know-how, you can directly create them from config, also, please translate to English before you send, its quite annoying for me to translate it again

**Comment by DragonfireHD** [comment]
![Screenshot_20200426_125232_com mojang minecraftpe](https://user-images.githubusercontent.com/50929188/80305438-f3140b80-87bc-11ea-80fd-7f86c67f6c2b.jpg)

Das ist mit OP obwohl keine permission gibt

![Screenshot_20200426_125308_com mojang minecraftpe](https://user-images.githubusercontent.com/50929188/80305450-07580880-87bd-11ea-886f-0f16a1938106.jpg)

Das ist das was ich meine man sieht denn command nicht mehr als normaler Spieler

**Comment by DragonfireHD** [comment]
I thought you can fix the plugin CommandCreator

**Comment by Johnsonk79** [comment]
I have no idea what you mean right now, you make no sense at all, at first, you are talking about a suggestion to implement command creation in mineflow using config, I told u its possible, and now u are saying you thought I can fix the plugin???

**Comment by DragonfireHD** [comment]
Ich sagte auch kann kein gutes English und es ging alles um ein Plugin Vorschlag nicht um dieses Plugin

**Comment by Johnsonk79** [comment]
is your problem solved now? you should close this issue if it yes, I'm telling you its possible to create commands in config of mineflow

**Comment by DragonfireHD** [comment]
Sie haben mich nicht zu gehört weder mich mich nicht verstanden aber das sie sagen ich soll die denn issue schließen ist das Zeichen das sie unfreundlich sind ganz ehrlich ich habe nett gefragt aber man sieht mal wieder das man gleich hier anders behandelt wird /das Thema ging die ganze Zeit um ein Plugin Vorschlag das ihr ein CommandCreator plugin erstellen könntet es ging nicht um mineflow deswegen der Titel

**Comment by DragonfireHD** [comment]
Can you make a CommandCreator Plugin

**Comment by Johnsonk79** [comment]
mineflow is a command creator plugin....

**Comment by Johnsonk79** [comment]
That is the first thing I said....

**Comment by DragonfireHD** [comment]
Ok how can i create a Command

**Comment by DragonfireHD** [comment]
I dont can english so good

**Comment by Johnsonk79** [comment]
please close this issue and make another called **How do I use this plugin**

**Comment by DragonfireHD** [comment]
Entschuldigung für die diskussion das hakt das wenn man andere Sprachen nicht verstehen kann 😂

**Comment by Johnsonk79** [comment]
use a frickin translator thats even what u said omg
