### ISSUE TITLE
[Question] How can we add a custom model 

### ISSUE THREAD

**Issue by sweatyrayan** [aieuo/Mineflow#111]
### Question

Title says it all

### Plugin Version

latest

**Comment by aieuo** [comment]
What is the custom model?

**Comment by sweatyrayan** [comment]
a custom geometry for a entity

**Comment by aieuo** [comment]
I see. You can't add it now, but I might implement it in the future.

**Comment by sweatyrayan** [comment]
Ok 👍🏻
