### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sweatyrayan** [aieuo/Mineflow#113]
### What happened?

When i add a recipe, with the trigger ¨When ¨test¨ button on a form was clicked (test)¨, and then when I restart the server it stops working. 

So it just stops working and when I try to add it again, it just doesnt work and its annoying to add it after every restart.

**Before restart**

![IMG_0372](https://user-images.githubusercontent.com/59512147/152654710-c51e3168-0a97-45cb-933c-4b9a3a569763.jpeg)

**After restart**

![IMG_0373](https://user-images.githubusercontent.com/59512147/152654721-2edcbcb2-0cf1-482f-8f3e-2ced43a1ee83.jpeg)

### Plugin Version

latest

### Server Version

 4.0.8

### PHP Version

8.0

### Server OS

linux

**Comment by MRizaaa** [comment]
You can add command (example "default") and add Command Button enter command (example: " default") and recipe triggered commamd button not bug

**Comment by MRizaaa** [comment]
yes i know it can be fxed if "Command-Button" on trigger Not "Button"

Command-Button trigger when server restart will not reset trigger

so use "command-button"

**Comment by MRizaaa** [comment]
enter the same command
