### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by MRizaaa** [aieuo/Mineflow#114]
### Question

How to send data from (Custom form input) to recipe? Example I write "test" in the input form and send Message "test"

（カスタムフォーム入力）からレシピにデータを送信する方法は？例入力フォームに「test」と入力し、メッセージ「test」を送信します

### Plugin Version

2.8.0

**Comment by sweatyrayan** [comment]
Action:
`Send the input form (your input form name) to target and put the result in input`
`Send message ¨{input}¨ to target´s chat field`

**Comment by MRizaaa** [comment]
Close
