### ISSUE TITLE
Toggle button 

### ISSUE THREAD

**Issue by MRizaaa** [aieuo/Mineflow#115]
### Question

how to do custom form (toggle button) if the toggle is turned on and submitted to execute the recipe?

トグルがオンになっていて、レシピが実行のために送信された場合、カスタムフォーム（トグルボタン）をどのように実行しますか？

### Plugin Version

2.8.0

**Comment by sweatyrayan** [comment]
Set the trigger of the recipe to `Form>(Recipename)> button`

**Comment by sweatyrayan** [comment]
when you create the button you get a message like {form.data[0]} <- true ; false) you can use that I think with the `script> add condition> script> compare to the character string.`

**Comment by MRizaaa** [comment]
Thanks but I don't understand after click "compare to the character string"

**Comment by MRizaaa** [comment]
Thanks but I don't understand after click "compare to the character string"

**Comment by MRizaaa** [comment]
what should i write in "compare to the character string"

**Comment by MRizaaa** [comment]
Thanks :)

**Comment by MRizaaa** [comment]
how to make "Input Form" Execute with the words we set how?

**Comment by sweatyrayan** [comment]
No problem
