### ISSUE TITLE
How to create a Command 

### ISSUE THREAD

**Issue by DragonfireHD** [aieuo/Mineflow#12]
Can you me help for a Command create

How can i make a command
I need a command where you can teleport on different worlds and every player can be blessed

**Comment by aieuo** [comment]
You can create command by following steps

Add command:
1. run /mineflow
2. click the `Manage command trigger > Add` button and enter the information of command.

Create Recipe:
3. run /mineflow
4. click the `Manage recipe > Add` button to add a recipe.
5. click the `Edit action > Add action` button.
6. click the `Command > Execute a command` button to enter the teleport command.

Links the command to the recipe:
7. back to the Recipe menu and click the `Edit trigger > Add trigger` button.
8. click the `Command` button and enter the command you created in step 2.

**Comment by DragonfireHD** [comment]
Ok
