### ISSUE TITLE
[Question] Enchant

### ISSUE THREAD

**Issue by MRizaaa** [aieuo/Mineflow#121]
### Question

How to enchant item with mineflow without adding items in inventory (set of enchant items in hand)

### Plugin Version

2.8.0

**Comment by aieuo** [comment]
You can use `Inventory > Set item in hand` action.

**Comment by sweatyrayan** [comment]
U have alot of open issues, maybe try closing the one´s that are solved?

**Comment by MRizaaa** [comment]
@sweatyrayan okey, sorry
