### ISSUE TITLE
[Question] How to check the xp level of a player

### ISSUE THREAD

**Issue by ricky074game** [aieuo/Mineflow#124]
### Question

In my action, I tried the variable {xp_level}. However, it is failing. What is the correct action command in order to check the level of a player?

**Comment by sweatyrayan** [comment]
I think u can use 

`Script > if> Script> compare to the numbers> {xp_level} = 1
Send message hi `

Im not sure tho, i'll have to try it out

**Comment by sweatyrayan** [comment]
Aaah ok 👍
