### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by sweatyrayan** [aieuo/Mineflow#128]
### Question

How can I send a message to {args.0}?

So for example the player does `/message player1 hi`
Then it sends the message `hi` to `player1`
How can I make this?

### Plugin Version

latest

**Comment by MRizaaa** [comment]
I think I can but with the form

**Comment by sweatyrayan** [comment]
How?
Because {args.0} is not a Player Variable...

**Comment by aieuo** [comment]
You can get a player variable by using the `Player > Get player from player name` action.

**Comment by sweatyrayan** [comment]
Thank you 👍

**Comment by sweatyrayan** [comment]
@aieuo 
Why does this not work?

`When a player executes the command /test

get player form player name and put it in test
send the message ¨hi¨ to test´s chat field`

**Comment by aieuo** [comment]
Can you show me a screenshot of the recipe?

**Comment by sweatyrayan** [comment]
Yeah

**Comment by aieuo** [comment]
Thanks

Insert `Send message "{speler}" to target`s chat field` action and check the value of the variable.

**Comment by sweatyrayan** [comment]
Also, when I put a other action (send message to everyone) after `Get player from player name` it doesnt work.

**Comment by aieuo** [comment]
I think the trigger is not working. If the action is not working correctly, some error should be displayed.  
Could you send me an exported file of that recipe?

**Comment by sweatyrayan** [comment]
[bugg.zip](https://github.com/aieuo/Mineflow/files/8226133/bugg.zip)
I cant upload a json file here, so you need to unpack the zip

**Comment by aieuo** [comment]
The target type of that recipe is `specified player` but it does not support a variable, so you should use `player who executed`.
![image](https://user-images.githubusercontent.com/35859665/157804942-13050c0d-4cd6-49c0-b716-aeffc5a08201.png)

**Comment by sweatyrayan** [comment]
Thank you!
I wanna thank you for making such a cool plugin and helping me all the time.
Just the fact that it is easy to learn and so simple.
