### ISSUE TITLE
[Question] How to empty or even remove a entity from the list variable?

### ISSUE THREAD

**Issue by ricky074game** [aieuo/Mineflow#134]
### Question

I create the list variable game_player_skywars. I put on {target.name} into it.
When I try to delete the variable inside the list, using {target.name} again. It doesn't remove it.
It keeps the list intact and shows no error. 
I put the variable name as game_player_skywars and the variable key as {target.player}

How do I fix this?

**Comment by aieuo** [comment]
Currently `Remove a value from the list variable` is deleting a value using an index(position numbers in the list starting from 0) and there is no way to remove a value using a specific value.
I will add an action to do that soon.
