### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by logannn61** [aieuo/Mineflow#138]
### Question

How do i run a command by the console instead of the player

**Comment by logannn61** [comment]
Where is that located 
![4B094704-C882-4370-9CB7-00F0DC526675](https://user-images.githubusercontent.com/100093353/156883008-90eb33ea-26a2-4283-a278-f793e9ebd0cd.png)
I am searching the key word console here

**Comment by sweatyrayan** [comment]
![Uploading 46F2BCF5-29D2-4656-ADA4-71B48D476ACB.jpeg…]()

**Comment by sweatyrayan** [comment]
You dont have your permission set to 2

Use `/mineflow permission <name> <permission>`

In console

**Comment by sweatyrayan** [comment]
![Uploading 516CEAC9-3AF2-4BCF-8FEB-37A923B5D99C.jpeg…]()

**Comment by sweatyrayan** [comment]
![IMG_1626](https://user-images.githubusercontent.com/59512147/157102165-464dab8e-0624-4c50-a86a-55a3e051ecc4.jpeg)

**Comment by logannn61** [comment]
okay that worked thanks
