### ISSUE TITLE
[Suggestion] Floating Text

### ISSUE THREAD

**Issue by sweatyrayan** [aieuo/Mineflow#148]
### Question

Any idea of adding a floating text action that we can customize?
Like the WFT plugin on poggit https://poggit.pmmp.io/p/wft

### Plugin Version

latest

### Additional Information

![image](https://user-images.githubusercontent.com/59512147/159332120-e1c4390d-daab-4fcf-9c96-7e039abbe365.png)

**Comment by aieuo** [comment]
There is currently no way to do that, but I am considering supporting it in the next major version.
