### ISSUE TITLE
[Bug]  Show Particle action error

### ISSUE THREAD

**Issue by sweatyrayan** [aieuo/Mineflow#149]
### What happened?

When I try to create the action `Show Particle`
I can create other actions but not show particle.
I get this error.

![image](https://user-images.githubusercontent.com/59512147/159452392-b80d4142-462c-4e55-8e7e-7d3df7e3bfa1.png)

The recipe
[bug.zip](https://github.com/aieuo/Mineflow/files/8323084/bug.zip)

### Steps to reproduce

1. Go in the WhileTask action
2. Create the action `Show particle`

### Plugin Version

latest

### Server Version

4.2.0

### PHP Version

8.0.15

### Server OS

linux

**Comment by aieuo** [comment]
Could you send me an exported file of the recipe? I think it is a bug that is a related variable before those actions, but I can't reproduce it.

**Comment by sweatyrayan** [comment]
I am sorry for the late response, but I realised that it is a very complicated, messy recipe.
I made a other recipe with the same functions and it works.
