### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by sweatyrayan** [aieuo/Mineflow#151]
### Question

How can I pass local variables values from a recipe to a other recipe?

**Comment by aieuo** [comment]
If you use `Callback the other recipe.`, you can pass variables by setting `Setting arguments and return values` in the destination recipe.

**Comment by sweatyrayan** [comment]
thanks I will try

**Comment by sweatyrayan** [comment]
Why does this not work
[help.zip](https://github.com/aieuo/Mineflow/files/8382434/help.zip)
?

**Comment by aieuo** [comment]
![image](https://user-images.githubusercontent.com/35859665/161439870-8887b449-6097-4cdd-8730-8b4a91c25707.png)
The value of `Setting arguments` is the name of a variable to add to the destination recipe, so you should enter `hartjesaan` or change the values of the actions in the recipe "hartjes1" from `{hartjesaan}` to `{i}`.
and the return value is the name of a variable to add the source recipe.


---
![名称未設定ファイル drawio](https://user-images.githubusercontent.com/35859665/161441680-d35bc336-b1f9-4dec-8434-4c7e180d7fc0.svg)
