### ISSUE TITLE
[Question] Scoreboard

### ISSUE THREAD

**Issue by ricky074game** [aieuo/Mineflow#153]
### Question

For scoreboards, I have 2 specific questions.
1: is there anyway to leave the score part blank when creating a new score?
2: Can the score not be a number? Like a string?

**Comment by aieuo** [comment]
A score is a number, which is a Minecraft specification and you can't change it to a blank or a string. If you want to hide those scores, you need a resource pack.

You can use the `Set a score name on the scoreboard` action to display a string on the scoreboard as shown in the following image
![image](https://user-images.githubusercontent.com/35859665/160227151-989dc792-9801-4336-a38f-783ebdaa57f3.png)
and you can also use blanks in the score name.
