### ISSUE TITLE
Variable name of Player

### ISSUE THREAD

**Issue by DavidFlashCZ** [aieuo/Mineflow#17]
Everytime I try to put different variable than "target" it doesn't work. It shows, that player not found even tho in other actions like Send message to chat field it normally shows the name of the player in the variable.. Can you fix that please? Also I sent you a friend request on Discord to keep it touch. Thanks.

**Comment by aieuo** [comment]
I don't think that variable is a player variable.  
Could you show me the exported recipe here or in the discord?  
![image](https://user-images.githubusercontent.com/35859665/85271680-135b0080-b4b6-11ea-8717-d8fd74ae4e3a.png)
