### ISSUE TITLE
How to make permissions stay

### ISSUE THREAD

**Issue by logannn61** [aieuo/Mineflow#174]
How do I make it so when using the action give player permission it keeps the permission and doesn’t remove it after they leave?

**Comment by logannn61** [comment]
How do I do that? Could you make a template so I could understand, thanks

**Comment by aieuo** [comment]
I created a recipe to add permissions and upload it [here](https://github.com/Mineflow/Examples/blob/master/permissions.json). You can download and import it.

When you import it, the following recipes will be added.
- aieuo/permission/add
- aieuo/permission/remove
- aieuo/permission/get
- aieuo/permission/set
- aieuo/permission/player_on_join

You can call `aieuo/permission/add` and `aieuo/permission/remove` to add or remove permission to a player.
Examples:
![image](https://user-images.githubusercontent.com/35859665/170813873-49da745c-0070-439a-9982-2c25db291fc0.png)
![image](https://user-images.githubusercontent.com/35859665/170813888-c374394c-9d07-44a4-83fe-98e35a3d16ae.png)
