### ISSUE TITLE
[Question] How to add enchantment to item in hand?

### ISSUE THREAD

**Issue by sweatyrayan** [aieuo/Mineflow#178]
### Question

Wich variable should I use to add enchantment to item in hand?
Because {target.hand} doesnt work

### Plugin Version

latest

### Additional Information

![image](https://user-images.githubusercontent.com/59512147/180847488-4f1ffa4f-2be9-4f31-9a00-987650cb7e33.png)

**Comment by aieuo** [comment]
You should copy the item to local variable and then add enchantments and set the item to the player's hand.  

```mermaid
flowchart TB

A["Create variable from specified variable name.(target.hand, item)"] -->B
B["Add enchantment to item (item)"] --> C["Set item in hand (item)"]
```

**Comment by sweatyrayan** [comment]
It works, thank you
