### ISSUE TITLE
[Question] After restart all my recipes empty

### ISSUE THREAD

**Issue by sweatyrayan** [aieuo/Mineflow#180]
### Question

After I restart the server all my recipes are empty, no actions and no triggers

### Plugin Version

latest

**Comment by keenanyafiqy** [comment]
it might not a question, its a bug?

**Comment by sweatyrayan** [comment]
I dont know? Maybe I need to use the Save action?

**Comment by sweatyrayan** [comment]
Oh, I need to use the save action before i restart the server. Now it saves the actions and triggers

**Comment by sweatyrayan** [comment]
Still doesnt work after I put a entity plugin in my server
