### ISSUE TITLE
[Question] Why is this not working?

### ISSUE THREAD

**Issue by sweatyrayan** [aieuo/Mineflow#182]
### Question

When clicked on a Enchantment Table, nothing happens

### Plugin Version

latest

### Additional Information

![image](https://user-images.githubusercontent.com/59512147/181616390-89e7472e-f483-4720-9c39-2d1229571cf4.png)

**Comment by sweatyrayan** [comment]
@aieuo ?

**Comment by aieuo** [comment]
Please use the `contains` operator as comparison string or use `{block.name}` variable.  
I'm sorry for the late reply.

**Comment by sweatyrayan** [comment]
Ok thanks
