### ISSUE TITLE
[Bug]  change damage and number(count) of item

### ISSUE THREAD

**Issue by HikaruFadil** [aieuo/Mineflow#184]
### What happened?

When i tried to change damage of item, the result alwas like "change damage of <item> to damage <item>, it should be <item> to damage  (number/variable i inputed), same issue as changing count/number of item, whatever numbers or variable that i inputed, the result is the same thing. For example : input variable of <item>   i input {target.hand} ,then input numbers of <damage> i input 8,
 result always like this "change damage of {target.hand} To damage {target.hand} it should be "change damage of {target.hand} to damage 8".
Mybe next update y should check this anoying bug

### Plugin Version

2.10.0

### Server Version

4.7.3

### PHP Version

8.0

### Server OS

Linux

**Comment by aieuo** [comment]
You have to copy the item to local variable first and then change damage of item and set the item to the player's hand.
