### ISSUE TITLE
problem with using a form as a trigger

### ISSUE THREAD

**Issue by SupremePox** [aieuo/Mineflow#19]
whenever i use a form as a trigger for example a warp with a category selection it will work the first time but after reloading server or stopping to get back on it becomes completely unresponsive the catgorey ui would pop up but when i click a button instead of teleporting me it does nothing please fix the forms as a trigger would make life easier.

**Comment by aieuo** [comment]
Please try to click the `save` button on the recipe you added the trigger

**Comment by SupremePox** [comment]
alright

**Comment by SupremePox** [comment]
i did that multiple times and it didnt work also i am running dev build 96 i tried using the current one but it crashes everytime i click on a button also when i edit the trigger and then execute it somehow works? please fix

**Comment by SupremePox** [comment]
and also by form i meant using a button as a trigger doesnt work but whenyou use "when this form is submitted" it works

**Comment by aieuo** [comment]
It seems that the reason why it does not work after restarting is that the file permissions have changed and plugin cannot be saved.
 So, please try to change the permissions of the `plugin_data/Mineflow` directory using the chmod command etc.

**Comment by xDanub** [comment]
I have this issue aswell. Whenever I use a form using Mineflow to open a different plugin's form using a command, it will not open the other plugin's form. Here is a clip of it.

https://streamable.com/52hzc1

as always wonderful plugin :)

**Comment by aieuo** [comment]
@xDanub thank you for your report and clip. I'll check it.

**Comment by xDanub** [comment]
Yes no problem. Love the plugin so I hope this can be fixed!

**Comment by xDanub** [comment]
@aieuo I figured out the issue. The issue is when Form Buttons have the § character in them they do not trigger the Recipes connected to the buttons.

**Comment by xDanub** [comment]
https://streamable.com/8djkw0

**Comment by aieuo** [comment]
Ohh, now I get it. Thank you. I'll fix it soon.
