### ISSUE TITLE
Internal Server Error when trying to create a recipe

### ISSUE THREAD

**Issue by xDanub** [aieuo/Mineflow#2]
How to reproduce:
1. /mineflow
2. Click recipe
3. Type anything
4. Internal Server Error

**Comment by aieuo** [comment]
Thank you for the report.
I tried it, but I couldn't reproduce. So, could you show me the details of the error statement?

**Comment by xDanub** [comment]
Yes sorry for the long time for reply. Here you go:
``` thread/CRITICAL ErrorException: "file_put_contents(/plugin_data/Mineflow/recipes/hello.json): failed to open stream: Permission denied" (EXCEPTION) in "plugins/Mineflow_dev-31.phar/src/aieuo/mineflow/recipe/Recipe" at line 307
```

**Comment by xDanub** [comment]
thread/CRITICAL ErrorException: "file_put_contents(/plugin_data/Mineflow/recipes/hello.json): failed to open stream: Permission denied" (EXCEPTION) in "plugins/Mineflow_dev-31.phar/src/aieuo/mineflow/recipe/Recipe" at line 307

Not sure if it is my internet but the error doesn’t show in the blocks above so I reposted without it just incase

**Comment by aieuo** [comment]
Thank you. Fixed.

Please delete the plugin_data/Mineflow/recipes folder, update the plugin and restart it.

**Comment by xDanub** [comment]
Thanks so much!
