### ISSUE TITLE
[Question] Why does this not work? 

### ISSUE THREAD

**Issue by sweatyrayan** [aieuo/Mineflow#215]
### Question

![image](https://user-images.githubusercontent.com/59512147/215558322-65a4f420-01c1-48bd-8c90-68976c8471fd.png)

i get the error that the variable {database{target.name}} doesnt exist 

### Plugin Version

latest

**Comment by aieuo** [comment]
Please remove the outer braces like 'database{target.name}'.

**Comment by sweatyrayan** [comment]
thank you 👍
