### ISSUE TITLE
[Crash] crash

### ISSUE THREAD

**Issue by RayanK0** [aieuo/Mineflow#232]
### What happened?

idk if its because of me but lately alot of things result in a crash or dont work
https://gyazo.com/af5d817212bec4f20fe25ef1e3bc73f4

List that cause crash:
When you try to create (any) variable
jukebox message
action bar message
When you try to edit a form through the edit trigger menu

There is maybe more stuff but i didnt try it

### Crash dump

Crash when you make a variable:

BAD PLUGIN: Mineflow

Error: Unhandled async exception: aieuo\mineflow\flowItem\form\EditFormResponseProcessor::rearrange(): Return value must be of type aieuo\mineflow\flowItem\form\EditFormResponseProcessor, null returned
File: plugins/Mineflow_v3.0.0 (1).phar/src/aieuo/mineflow/libs/SOFe/AwaitGenerator/Await
Line: 587
Type: aieuo\mineflow\libs\SOFe\AwaitGenerator\AwaitException
Backtrace:
#0 plugins/Mineflow_v3.0.0 (1).phar/src/aieuo/mineflow/libs/SOFe/AwaitGenerator/Await(334): aieuo\mineflow\libs\SOFe\AwaitGenerator\Await->reject(object TypeError#60749)
#1 plugins/Mineflow_v3.0.0 (1).phar/src/aieuo/mineflow/libs/SOFe/AwaitGenerator/Await(129): aieuo\mineflow\libs\SOFe\AwaitGenerator\Await->wakeup(array[2])
#2 plugins/Mineflow_v3.0.0 (1).phar/src/aieuo/mineflow/libs/SOFe/AwaitGenerator/Await(102): aieuo\mineflow\libs\SOFe\AwaitGenerator\Await::g2c(object Generator#39984, null, array[0])
#3 plugins/Mineflow_v3.0.0 (1).phar/src/aieuo/mineflow/ui/FlowItemForm(236): aieuo\mineflow\libs\SOFe\AwaitGenerator\Await::f2c(object Closure#101091)
#4 plugins/Mineflow_v3.0.0 (1).phar/src/aieuo/mineflow/formAPI/Form(172): aieuo\mineflow\ui\FlowItemForm->aieuo\mineflow\ui\{closure}(object pocketmine\player\Player#28608, int 1)
#5 plugins/Mineflow_v3.0.0 (1).phar/src/aieuo/mineflow/formAPI/ListForm(143): aieuo\mineflow\formAPI\Form->onSubmit(object pocketmine\player\Player#28608, int 1)
#6 plugins/Mineflow_v3.0.0 (1).phar/src/aieuo/mineflow/formAPI/Form(160): aieuo\mineflow\formAPI\ListForm->onSubmit(object pocketmine\player\Player#28608, int 1)
#7 pmsrc/src/player/Player(2114): aieuo\mineflow\formAPI\Form->handleResponse(object pocketmine\player\Player#28608, int 1)
#8 pmsrc/src/network/mcpe/handler/InGamePacketHandler(975): pocketmine\player\Player->onFormSubmit(int 8, int 1)
#9 pmsrc/vendor/pocketmine/bedrock-protocol/src/ModalFormResponsePacket(63): pocketmine\network\mcpe\handler\InGamePacketHandler->handleModalFormResponse(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket#63237)
#10 pmsrc/src/network/mcpe/NetworkSession(433): pocketmine\network\mcpe\protocol\ModalFormResponsePacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#102857)
#11 pmsrc/src/network/mcpe/NetworkSession(377): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket#63237, string[7] e...1..)
#12 pmsrc/src/network/mcpe/raklib/RakLibInterface(198): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[53] cO.`d2.b....0..`c..C.g..:.u....f..(..3021.....&,.....)
#13 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[62] .>>.;|&>...?G..x.........&F..g..0.."gC.0q{..V.5.<.d.Cw.F9.....)
#14 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#28259)
#15 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#16 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
#17 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#18 pmsrc/src/Server(1688): pocketmine\snooze\SleeperHandler->sleepUntil(float 1685385845.5026)
#19 pmsrc/src/Server(1068): pocketmine\Server->tickProcessor()
#20 pmsrc/src/PocketMine(336): pocketmine\Server->__construct(object BaseClassLoader#5, object pocketmine\utils\MainLogger#2, string[16] /home/container/, string[24] /home/container/plugins/)
#21 pmsrc/src/PocketMine(359): pocketmine\server()
#22 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

Code:
[578] 		$this->sleeping = true;
[579] 
[580] 		parent::reject($throwable);
[581] 		foreach($this->catches as $class => $onError){
[582] 			if($class === "" || is_a($throwable, $class)){
[583] 				$onError($throwable);
[584] 				return;
[585] 			}
[586] 		}
[587] 		throw new AwaitException("Unhandled async exception: {$throwable->getMessage()}", 0, $throwable);
[588] 	}
[589] 
[590] 	/**
[591] 	 * @internal This is implementation detail. Existence, signature and behaviour are semver-exempt.
[592] 	 */
[593] 	public function isSleeping() : bool{
[594] 		return $this->sleeping;
[595] 	}
[596] }

### Plugin Version

3.0.0

### Server Version

4.6.1 i think

### PHP Version

8.0

### Server OS

linux

**Comment by aieuo** [comment]
Thank you for your report.
It was fixed in https://github.com/aieuo/Mineflow/releases/tag/3.1.0
