### ISSUE TITLE
 How to use url images?[Question] 

### ISSUE THREAD

**Issue by justauser001** [aieuo/Mineflow#238]
### Question

Can u tell me how to use url images in mineflow form

### Plugin Version

2.12.0

**Comment by aieuo** [comment]
Currently, it is not possible to use url images.  
I will implement it in the next update.

**Comment by aieuo** [comment]
Now you can specify a URL in the image field of the form.
Please download and use dev build 379 from poggit.

https://poggit.pmmp.io/ci/aieuo/Mineflow/Mineflow/dev:379
[direct link](https://poggit.pmmp.io/r/212620/Mineflow_dev-379.phar)
