### ISSUE TITLE
[Question] - How can I make Custom Forms work?

### ISSUE THREAD

**Issue by NecroSama8** [aieuo/Mineflow#246]
### Question

Hello! I have been doing some tests with custom forms, believe me I have tried almost everything, however, I have not been able to figure out how it works, do you have any ideas?

My goal is to make a custom form that sends an amount of money that the target specifies. The number that is placed in the number input would be placed in a local variable called {count}, and the name of the player that is chosen would be placed in another variable local call {user}, however I haven't figured out how to get those things put into variables, any help?
![Screenshot_20240107_193757](https://github.com/aieuo/Mineflow/assets/112836351/602a4b0d-83d7-4f4f-bedf-c90bccfe87d2)

**Comment by Ryz-pixel** [comment]
I didnt test this, but you can try

First you should get its textboxes and options variable by editing them in the form designer. 
The variable should be at the top.
![image](https://github.com/aieuo/Mineflow/assets/88238472/c7604708-ce13-46e4-a4bb-2cf524872a8b)

Then to put the forms data in a variable do this:

Create a recipe 
Triggers:
When the form issubmitted
Actions:
Add local number variable with the value of {form.data[1]} and put it in {count}


For the other option with the user, you should do the same but the variable should be like {form.selected[0]}

**Comment by NecroSama8** [comment]
Thank you very much, believe me, it has been very helpful to me! 🥹
