### ISSUE TITLE
[Question] Variables

### ISSUE THREAD

**Issue by NecroSama8** [aieuo/Mineflow#247]
### Question

Is it possible to make a variable whose value is, for example, {potato}, without this value ({potato}) being another variable? That is, in this case {potato} is shown as such in the other actions, for example `Send a message to the target->Hello World! {potato}`. {potato} should be displayed just like this. Is there a way to do it? I don't know if I made myself understood.

### Plugin Version

2.5.2

**Comment by aieuo** [comment]
There is no way to do that for Mineflow 2.5.2
If you use Mineflow 3.4.0(currently under development) you can write `Hello World! \{potato\}` to escape the curly brackets. However, this version has many changes from 2.5.2 and once you upgrade to 3.4.0, you can't downgrade the saved data to 2.5.2.

If you want, you can download 3.4.0 from here: https://poggit.pmmp.io/ci/aieuo/Mineflow/Mineflow/dev:400.
(Make sure to make a backup of your data before updating to 3.4.0)
