### ISSUE TITLE
Got double tap when clicking on a Slapper

### ISSUE THREAD

**Issue by Adam1609** [aieuo/Mineflow#25]
Installing Mineflow on the server will result as double tap on it. Happen on Mineflow_dev-136. Is it intended or a glitch? Can you please check?

**Comment by aieuo** [comment]
Thank you for your report.
I checked, but I couldn't reproduce it. Please tell me more about it in screenshots or something.

**Comment by aieuo** [comment]
I'm sorry... It was a glitch caused by this plugin. I fixed it.
