### ISSUE TITLE
Translation Misses

### ISSUE THREAD

**Issue by xDanub** [aieuo/Mineflow#3]
There are a few places in the /mineflow model that still had Japanese language and it’s hard to understand what those buttons do. I will try to list them here:
1. /mineflow form description
2. Permission drop down 
![A4C8E8AF-003D-49E6-A06D-664C67296DB3](https://user-images.githubusercontent.com/41587198/78706981-9a480600-78d5-11ea-9c35-b5ad5bbf44d7.png)
![Uploading D81F30F9-B299-46FD-9789-58ABB0DFFBFD.png…]()

**Comment by xDanub** [comment]
![546ECC3F-2622-4046-B460-9BAF4BAF42C5](https://user-images.githubusercontent.com/41587198/78707090-c06da600-78d5-11ea-8a1c-a824bcc9475b.png)

**Comment by aieuo** [comment]
The translation work is now underway.
Thank you for your help with translation misses and confusing translations.

**Comment by xDanub** [comment]
You’re welcome! I love the plugin and the creativity of it! : )
