### ISSUE TITLE
Double message shown in console

### ISSUE THREAD

**Issue by Adam1609** [aieuo/Mineflow#30]
When I try and do something in the Mineflow form, the console start to double the message and even execute twice of the command.

**Comment by Adam1609** [comment]
[
![Capture5](https://user-images.githubusercontent.com/16860075/100743655-2aabfb80-340f-11eb-95d2-71c8ec1ae074.PNG)
](url)
This is the picture of my console when executing a recipe from Mineflow

**Comment by aieuo** [comment]
Thank you for the report. I tried, but I could not reproduce it. Would you send the recipe you have executed?

**Comment by Adam1609** [comment]
`{
    "name": "123",
    "author": "Adam1609",
    "detail": "1",
    "plugin_version": "1.0.2",
    "recipes": [
        {
            "name": "1 and 2",
            "group": "miner1",
            "author": "Adam1609",
            "actions": [
                {
                    "id": "commandConsole",
                    "contents": [
                        "givelootbox {target} epic 1"
                    ]
                },
                {
                    "id": "commandConsole",
                    "contents": [
                        "givemoney {target} 100000"
                    ]
                }
            ],
            "triggers": [
                {
                    "type": "missionreward",
                    "key": "3e07db6c-6eb8-2ab3-7436-131dca69db61",
                    "subKey": ""
                },
                {
                    "type": "missionreward",
                    "key": "958a3dab-655c-c938-27bc-e55e94880a4b",
                    "subKey": ""
                }
            ],
            "target": {
                "type": 0,
                "options": []
            },
            "arguments": [],
            "returnValues": []
        }
    ],
    "commands": [],
    "forms": [],
    "configs": []
}`

This is the recipe I use

**Comment by aieuo** [comment]
thank you. I'll check it.

**Comment by aieuo** [comment]
Hmmm, imported and executed, but still could not reproduce. I'll continue to check and fix it if I find the cause.

**Comment by Adam1609** [comment]
It could be Mission problem, I will open the issue at its plugin to see

**Comment by Adam1609** [comment]
Close this issue now
