### ISSUE TITLE
[Suggestion] Adding new event trigger

### ISSUE THREAD

**Issue by Adam1609** [aieuo/Mineflow#31]
This is either suggestion or requested, but I think there should be new events like:

- When player kill another player
- When player kill an entity

**Comment by aieuo** [comment]
thank you for your suggestion. i'll add them.

**Comment by aieuo** [comment]
There was already a "when a player dies" event, so I added "killer" to it.

**Comment by Adam1609** [comment]
I just test the new event, it worked btw. I will inform you if there is any bug, keep up the good work 👍

**Comment by aieuo** [comment]
thank you!

**Comment by Adam1609** [comment]
[16:20:22] [Server thread/WARNING]: [Mineflow] [Increase the mission step.] {killer} is not Player variable.
[16:20:22] [Server thread/WARNING]: [Mineflow] Failed to execute the action. : test4 > Increase the mission step.

Ok so I just found in the console
