### ISSUE TITLE
[Suggestion] Adding new trigger event <continued>

### ISSUE THREAD

**Issue by Adam1609** [aieuo/Mineflow#32]
I am doing some RPG story driven server and the last month this plugin is super good for me to use. Apparently there is still something missing in the Event, so I have a suggestion for you:

- When player pick up an item

- Adding a break a block at position (I only see touch a block, and I don't know if there is a event to that)

- Set player health, max health and other attributes

- When player standing at position

These are my suggestion, I hope you will do it. Keep up the good work!

**Comment by aieuo** [comment]
Thank you for your suggestion.

> When player pick up an item  

I'll add it.


> Adding a break a block at position  

I think it already exists as `When a player breaks a block`

> Set player health, max health and other attributes  

Does it mean that when a player's Attribute is changed for some reason, mineflow will call a trigger?. 
If yes, there is no such event in pmmp, so I can't add it...

> When player standing at position  

I think this can be implemented with an `when a player moves`, an `if` action, and a `if the entity is in the specified area` condition.
If you don't see the "when a player moves", you can enable it with `setting` > `event`.

**Comment by Adam1609** [comment]
I don't see the breaking block at position. Can you point out where I can find it? Cause I have looked everywhere :(

**Comment by aieuo** [comment]
Is it a Trigger or an Action?

**Comment by Adam1609** [comment]
The only thing I saw in the Trigger is touching a block at position, not breaking.

**Comment by aieuo** [comment]
Please run `/mineflow` and click `Setting > Event` button to check that `When a player breaks block` is enabled.

![image](https://user-images.githubusercontent.com/35859665/102439887-76db7a80-4062-11eb-9023-6b17deecc811.jpeg)

**Comment by Adam1609** [comment]
Oh I understand, thanks so much, will close this issue now
