### ISSUE TITLE
Adding new language support + Form bug

### ISSUE THREAD

**Issue by Adam1609** [aieuo/Mineflow#34]
1. Beside English and Japanese language, can I make a pull requests and add my language into the plugin?

2. This bug does not affect much but when creating a form, edit the name will create another form. But editing the dupe form will not create another one.

**Comment by aieuo** [comment]
1. Of course. I'd be very grateful for that.
2. I'll fix it. Thank you for your report.

**Comment by Adam1609** [comment]
I will close this issue, Currently I don't have time to contribute the language file to the plugin now
