### ISSUE TITLE
Does not say the permission node for commands set to require custom permissions.

### ISSUE THREAD

**Issue by Xd-pro** [aieuo/Mineflow#35]
I can't find anywhere I can get this permission node.

**Comment by aieuo** [comment]
I'm sorry. I don't get it.  
Do you mean about this image?  
![image](https://user-images.githubusercontent.com/35859665/103901093-093fdd00-513c-11eb-852d-5e8c266ac031.png)

**Comment by Xd-pro** [comment]
I mean does it use, for example mineflow.command.<permission> or does it use mineflow.<permission> or just <permission>?

**Comment by aieuo** [comment]
I got it. You can use anything with or without `mineflow.`.
