### ISSUE TITLE
Bug + I need some help

### ISSUE THREAD

**Issue by sweatyrayan** [aieuo/Mineflow#37]
Bug

If i click on: create a variable i get a internal server error.

Help

two things, first of all how can i make someone teleport to specific coordinates? There is a teleport option but i dont know how it works.
Second issue i have been getting is, how can i make when a player clicks on button1 from a form that they open another form?

**Comment by aieuo** [comment]
> Bug

Please send the error log shown in console.

> Teleport

You can add `World > create position variable` before the teleport option. like this:
![image](https://user-images.githubusercontent.com/35859665/103902703-3c836b80-513e-11eb-9985-d2061b4314c5.png)

> Form

You can do it by following steps.

1.  Create a new recipe.
2. Click `Edit trigger > Add trigger > Form` button on recipe menu to add trigger.
3. Add a `Form > Send a form` action to the recipe.
