### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by xDanub** [aieuo/Mineflow#4]
First off, I love this plugin! I think it will help people with little knowledge in coding have a new way to create these things. 

My suggestion is though, that you add an option to have a command you create run other commands after it is ran. 
For example:
Let’s say I create a new command called /staff if I could it to where when players do /staff it also runs the commands:
/gamemode spectator
/give {player} diamond_ore 10

So that way the commands we make can do more than just give information. Thanks for making this plugin it’s amazing! : )

**Comment by aieuo** [comment]
Thank you for your suggestions.
I think it can be implemented with the following steps

1. Add a recipe
2. Add a trigger for the command /staff
3. Add a command to be executed at the same time in [Execute command] of the action

I'm sorry if this is a misplaced answer.

**Comment by Johnsonk79** [comment]
Hello, I can't really figure out how you can give an item to the player when they run a command

**Comment by aieuo** [comment]
Please try using the actions "Item > Create item variable" and "Inventory > Add items to inventory".

You can create a variable with the item information in "Create item variable" and enter the name of the item variable you created in "Add items to inventory". Then you can give items to the player.
