### ISSUE TITLE
how to make a player input form?

### ISSUE THREAD

**Issue by dragonkid608** [aieuo/Mineflow#44]
![Screen Shot 2021-02-06 at 3 14 53 PM](https://user-images.githubusercontent.com/72533566/107131745-1d3b4380-688e-11eb-8160-7370029bf939.png)
to execute a command like sw stats {(get the player name form the form)}

**Comment by aieuo** [comment]
The value inputted in the first element will be put into `{form.data.0}`.(the second is `{form.data.1}` and the third is `{form.data.2}`...) So in this case, you can execute a command with `sw stats {form.data.0}`.
