### ISSUE TITLE
[Question] How to add particle (or firework particle) to a specific player (or entity)?

### ISSUE THREAD

**Issue by Adam1609** [aieuo/Mineflow#46]
I have been trying to add particle but seems that I can't find the particle section. Is it implement yet? If it is, can you guide me to use this?

**Comment by aieuo** [comment]
![image](https://user-images.githubusercontent.com/35859665/110077132-f73f8b00-7dc8-11eb-9b43-7fcf9a3b14ab.png)

It will be shown in the world category. If not, please make sure that your permission is set to 1 or higher.

**Comment by Adam1609** [comment]
Thanks for the help, I have found it. Will close the issue
