### ISSUE TITLE
Console

### ISSUE THREAD

**Issue by xKurt21** [aieuo/Mineflow#48]
How do I run a command from the console?
For eg. I created a /dailyreward command and then the console will give the player the rewards

I already did it but the console didn't give it, the player who executed the command did
There's no option on the form about the console

**Comment by aieuo** [comment]
There will be an "Execute a command from console" action in the command category.  
![image](https://user-images.githubusercontent.com/35859665/111294357-9861f780-868d-11eb-9855-bdbcc7bc6c84.png)

If not, please run `/mineflow permission <your name> 1` from the console

**Comment by xKurt21** [comment]
Thank you very much! 
Also, can u include it in the description, it'll be helpful so players don't ask anymore tho. Anyways thanku sm

**Comment by xKurt21** [comment]
I have a question.

I added a command _/hello_ which has a _/sendmessage {player} hi_ (command from console) and console says player not found? Idk what to do
