### ISSUE TITLE
[Suggestion] Executing a recipe with command

### ISSUE THREAD

**Issue by Adam1609** [aieuo/Mineflow#49]
The recipe is great for creating something like a plugin. But we have to go to the UI and execute the recipe, which will take a lot of time. So the command I am suggest is more like an addition: /mineflow execute (name of the recipe). When a player with the permission (like OP) input this command, the recipe will be executed to the person who input the command.

I know that this is kinda like: "You can create a command using Add Command" but it is just a suggestion

**Comment by aieuo** [comment]
Thank you for your suggestion.
I'll add that.

**Comment by aieuo** [comment]
I added the commands as `/mineflow recipe execute <name> [group]` and `/mineflow recipe execute <group/name>`.
