### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Johnsonk79** [aieuo/Mineflow#5]
Using newest build

<img width="1712" alt="Screenshot 2020-04-14 at 2 45 48 PM" src="https://user-images.githubusercontent.com/45489804/79194185-b6f8b680-7e5e-11ea-9051-0bc933d6bc2d.png">

**Comment by aieuo** [comment]
Thank you for the report. I'll fix it soon.

**Comment by Johnsonk79** [comment]
thx
