### ISSUE TITLE
can i make a "always active" recipe

### ISSUE THREAD

**Issue by dragonkid608** [aieuo/Mineflow#58]
so it doesnt need any trigger and be always active?

**Comment by aieuo** [comment]
There is no option just for that, but you can use `Event > When the server start` trigger and `Script > Repeat for every specified seconds while conditions are match.` action to make recipe always active.

**Comment by dragonkid608** [comment]
Thanks but how do i use like for example
When the server starts ->
Repeat uf conditions are matched
If entity is in radio of 260 93 - 31 260 95 - 34
Put item variable (ítem) in entitys inventory

**Comment by aieuo** [comment]
I made an example. To use it, please rename .txt to .json and import it.
[always_active1.txt](https://github.com/aieuo/Mineflow/files/6252990/always_active1.txt)

raw text:
```
When the server start
~~~~~~~~~~~~~~~~~~~~
Put the position(10,0,10,world) into a variable named pos1.
Put the position(20,200,20,world) into a variable named pos2.

======== whileTask(20) ========
~~~~~~~~~~~~~~~~~~~~~~~~~~~
============= if ===============
If target is in the range of pos1 to pos2.
~~~~~~~~~~~~~~~~~~~~~~~~~~~
Send message "area" to target's chat field.
================================
================================
```

The `whiteTask (Repeat for every specified seconds while conditions are match.)` is used for make recipe always active, and the `if` action is used for to check if a player is in the area.
Please make sure to change the target type to `all online players` from `Change the target` button for this way.

**Comment by dragonkid608** [comment]
but how all online players, what variable?

**Comment by aieuo** [comment]
there is a button on the recipe menu
![image](https://user-images.githubusercontent.com/35859665/113497606-ae523200-9540-11eb-90f6-0301dbe7954f.png)
