### ISSUE TITLE
Could not load plugin 'Mineflow': Incompatible network protocol version

### ISSUE THREAD

**Issue by DarcZera** [aieuo/Mineflow#59]
Server thread/ERROR Could not load plugin 'Mineflow': Incompatible network protocol version (plugin requires one of: 389, 390, 407, 408, 419, 422, 428)

![image](https://user-images.githubusercontent.com/81932193/114285856-b1618c80-9a30-11eb-8c1d-cccafd739202.png)

**Comment by paul-schwarz123** [comment]
I have the same problem

**Comment by DarcZera** [comment]
hey bro. I have another plugin that needs to update the protocol, can you tell me how to do it?

**Comment by aieuo** [comment]
You can add 431 to `mcpe-protocol` in the `plugin.yml` like [this](https://github.com/aieuo/Mineflow/commit/c8c2d6c59d81c61ab418d597a6996540d9d6c235)
