### ISSUE TITLE
[Bug#2]

### ISSUE THREAD

**Issue by Johnsonk79** [aieuo/Mineflow#6]
After I create a form and click on the 
``List of Recipes triggered by this form``
I got kicked and this is what showed in console

<img width="1728" alt="Screenshot 2020-04-14 at 8 18 30 PM" src="https://user-images.githubusercontent.com/45489804/79224270-62206480-7e8d-11ea-81a6-e362f9384625.png">

**Comment by aieuo** [comment]
Thank you for your report. I'll fix it.
