### ISSUE TITLE
target variable

### ISSUE THREAD

**Issue by Lolker222** [aieuo/Mineflow#61]
why variable target gives the coordinates and not the name

**Comment by aieuo** [comment]
Please tell me more about it with the recipe you created, screenshots, etc.

**Comment by Lolker222** [comment]
![Screenshot_20210422_172333_com mojang minecraftpe](https://user-images.githubusercontent.com/77900340/115731122-8ad81580-a38f-11eb-886b-33c0c8708ee9.jpg)
![Screenshot_20210422_172344_com mojang minecraftpe](https://user-images.githubusercontent.com/77900340/115731132-8ca1d900-a38f-11eb-9d43-3498f12bcb3d.jpg)

**Comment by aieuo** [comment]
Thank you. I fixed it.
