### ISSUE TITLE
[Question] How to execute a form with a command?

### ISSUE THREAD

**Issue by Mencoreh** [aieuo/Mineflow#64]
I know it´s possible a dumb question but i´m newbie i just created like one custom command, so i created a form but i don´t know how to trigger it because there isn´t something like "edit trigger" in the form creation, i created this form 
![image](https://user-images.githubusercontent.com/84292106/123867271-be856d80-d8f3-11eb-807f-6812ecfbc471.png)
And i want to execute it with a slapper or a sign, **How to trigger a form?**

**Comment by aieuo** [comment]
To add trigger, you have to create a recipe and use `Form > send a form` action. and then you will find a `Edit trigger` button on recipe menu.

**Comment by Mencoreh** [comment]
> To add trigger, you have to create a recipe and use `Form > send a form` action. and then you will find a `Edit trigger` button on recipe menu.

Tysm, i warned that was probably a dumb question xD

**Comment by Mencoreh** [comment]
Now i have slappers in a shop and when i touch them the form appears
![image](https://user-images.githubusercontent.com/84292106/123904789-b3076600-d936-11eb-89e2-5ee18247e137.png)
![image](https://user-images.githubusercontent.com/84292106/123904809-bb5fa100-d936-11eb-81f4-8fc412bc3449.png)
