### ISSUE TITLE
Add a Delay action

### ISSUE THREAD

**Issue by Altamash347** [aieuo/Mineflow#68]
in a recipe, please add an action to add a delay.

Example:
If I want to add a recipe which will execute these two commands `say hi` and `say hello` but I want to add a 2 second delay between them, so I will add a delay action between those two command actions and then by executing the recipe it will add a delay between those two commands to be executed.

I hope you understand what I mean. sorry for bad English

**Comment by aieuo** [comment]
You can use the `Script > Wait` action for that feature.

**Comment by Altamash347** [comment]
thanks so much its working, you are really fast.
