### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Johnsonk79** [aieuo/Mineflow#7]
A feature that I think will be very useful, which is the 
`Player has permission`
condition in the conditions menu 

<img width="788" alt="Screenshot 2020-04-14 at 8 24 24 PM" src="https://user-images.githubusercontent.com/45489804/79224609-fab6e480-7e8d-11ea-9721-70fa51360e85.png">

And if possible, a new action that adds a permission to the player

Thanks a lot :D

**Comment by aieuo** [comment]
Thank you for your suggestion.
Does that mean the permissions granted by the /op command?

**Comment by Johnsonk79** [comment]
A permission like mineflow.use.command1, so that only some permission groups can use that command. 

Thanks a lot!

**Comment by aieuo** [comment]
Oh, I get it. I'll try to add them.
Thank you.

**Comment by Johnsonk79** [comment]
WOW Thank you so much!

❤️
