### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Ryz-pixel** [aieuo/Mineflow#71]
Ive been using your plugin alot lately, but i have some problems.

first of all how can i show  {form.data[0]} in the content of a form? I tried it and it says: Undefined index form.data.0

and second how can i do like that the script stops? 
i want if the player crouches the script stops and doesnt move damaged to target

![69096DE1-AD63-4203-944D-096BE2A59A0D](https://user-images.githubusercontent.com/88238472/128332023-955d26fb-8c9b-40e3-a18e-cb3e231a69b3.jpeg)

**Comment by aieuo** [comment]
> first of all how can i show {form.data[0]} in the content of a form? I tried it and it says: Undefined index form.data.0

The {form} variable is only available for recipes that added a form trigger

> and second how can i do like that the script stops?
> i want if the player crouches the script stops and doesnt move damaged to target

One way I can think of is to use a `Script > if` action, an `Entity > The entity is sneaking` condition and a `Script > Repeat for every specified seconds while conditions are match.` action.

![image](https://user-images.githubusercontent.com/35859665/128635399-ac8e7785-b435-4ad4-af77-ef364267c5df.png)
