### ISSUE TITLE
変数名から変数を作成する　について

### ISSUE THREAD

**Issue by Yuukurikaito** [aieuo/Mineflow#72]
変数名から変数名を作成するアクションのオプションにグローバル変数としても追加できるようにしてほしいです。

**Comment by aieuo** [comment]
変数名から変数を作るでグローバル変数を作れるようにすると保存できないプレイヤーのグローバル変数などが作れてしまうため用意していません。
文字列や数字の変数を作りたい場合、代わりに普通の`変数を作成する`アクションを使用してください

**Comment by Yuukurikaito** [comment]
わかりました
