### ISSUE TITLE
Please update to Minecraft Bedrock Edition v1.17.40 (protocol version 471)

### ISSUE THREAD

**Issue by ExplosionGaming** [aieuo/Mineflow#85]

**Comment by ExplosionGaming** [comment]
Still does not work

**Comment by aieuo** [comment]
open the above URL and click here:

![image](https://user-images.githubusercontent.com/35859665/139529202-195c6263-334b-4233-9604-bcbb9192df5c.png)

**Comment by ExplosionGaming** [comment]
I did that and applied it to my server. But when I tried it, it would just give me a internal server error.

**Comment by aieuo** [comment]
Please show me the error details

**Comment by ExplosionGaming** [comment]
![image](https://user-images.githubusercontent.com/92651856/139596560-dfb7f61f-193c-42ab-8262-15333e6f6064.png)

**Comment by ExplosionGaming** [comment]
I fixed it, Thanks anyway.
