### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ExplosionGaming** [aieuo/Mineflow#89]
Could you maybe add "If < amount > of players are in a area do < action >"?

**Comment by keenanyafiqy** [comment]
Just add by yourself >:(

**Comment by ExplosionGaming** [comment]
See that's the problem. I can't.

**Comment by ExplosionGaming** [comment]
Wow, I'm surprised that this issue is still open.

**Comment by keenanyafiqy** [comment]
Unless you close it.

**Comment by sweatyrayan** [comment]
Maybe try this,
**Recipe 1**

trigger
`When a player joins the server`

action
`create a global number variable named {test}`

**Recipe 2**
trigger
`When a player moves`

action
`Script if the player moves from {cords to cords}`
`if the player is in the selected area: {cords}`

`Script if {test} not contains 1`

`Add the value 1 to {test}`

**Recipe 3**
`Script`
`If the player moves from {cords to cords}`
`remove the value 1 of {test}`

**Recipe 4**
Compare to the numbers 

if {test} > 5
Send message to everyone ¨hi¨
