### ISSUE TITLE
Add a <player> selector here? It would be helpful

### ISSUE THREAD

**Issue by xDanub** [aieuo/Mineflow#9]
![E2125C9D-9F0E-45B4-BE6F-E0B7DD90504C](https://user-images.githubusercontent.com/41587198/79635786-99666e00-8138-11ea-9fb3-8ae36e34f530.png)

The reason why I ask is the command will return this:
`Added <player> to group `
It will not change <player>

**Comment by aieuo** [comment]
Try `{target}` instead of `<player>`.

**Comment by xDanub** [comment]
`Added <target> to the group successfully. `

**Comment by aieuo** [comment]
using `<target>`? Please try `{target}`.

**Comment by xDanub** [comment]
Worked.. sorry
