### ISSUE TITLE
Update to 4.0.0 (1.18.02)

### ISSUE THREAD

**Issue by ExplosionGaming** [aieuo/Mineflow#90]

**Comment by aieuo** [comment]
It's underway in [3.0-pm4](https://github.com/aieuo/Mineflow/tree/3.0-pm4) branch and almost finished, but I haven't checked it all works yet.  
Make sure that once you use Mineflow3.x, Mineflow2.x will not be able to load the saved data.

**Comment by ExplosionGaming** [comment]
So will the previous version of mineflow be compatible?
