### ISSUE TITLE
Position error

### ISSUE THREAD

**Issue by ExplosionGaming** [aieuo/Mineflow#97]
Error: Undefined property: pocketmine\world\Position::$level
File: plugins/Mineflow (7).phar/src/aieuo/mineflow/variable/object/PositionObjectVariable
Line: 24
Type: ErrorException

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: Mineflow

**Comment by aieuo** [comment]
Thank you for the report.
It was fixed by https://github.com/aieuo/Mineflow/commit/9df7412d08ce8e001cc4c7cc068c38c401cce3cc
