### ISSUE TITLE
question

### ISSUE THREAD

**Issue by sweatyrayan** [aieuo/Mineflow#99]
Is there any way to add a trigger when a player walks on a specific block?

**Comment by aieuo** [comment]
There is no such trigger, but you can add one with a custom trigger.

**Comment by sweatyrayan** [comment]
How?

**Comment by aieuo** [comment]
I created https://github.com/aieuo/MineflowExamples/blob/master/README.md#walk-on-specific-block
You can download the JSON file into the `mineflow/imports` folder and import it with `/mineflow recipe` command.  
To add the trigger to your recipe, click `EditTrigger > Add > Custom` and trigger name you have set (default is `walk_on_stone`)

**Comment by sweatyrayan** [comment]
I dont see a ¨When a player moves¨ trigger.

**Comment by aieuo** [comment]
You can see it by running `/mineflow` command and clicking `Setting > Event` button.

![image](https://user-images.githubusercontent.com/35859665/149064175-e2f6a0a3-36f6-47e6-9ce6-fc0ecdeca423.png)

**Comment by sweatyrayan** [comment]
Thanks it works, I completely forgot that you could turn it on in the settings. 😅
